# This is a basic workflow to help you get started with Actions

name: CI

on: [ push, pull_request ]

jobs:
  directories:
    runs-on: ubuntu-latest
    name: Get all directories with changed files
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed directories
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --dirstat-by-file --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs | tr " " "\n" | sed -n 'n;p')"
  show:
    runs-on: ubuntu-latest
    name: Show changed directories
    needs: directories
    if: ${{needs.directories.outputs.all}}
    steps:
      - name: Showing changed directories
        run: |
          directories="${{ needs.directories.outputs.all }}"
          for i in $directories; do 
            file="${i}action.yml";
            echo "working on ${file}";
            if [[ -f $file ]]; then
                echo "$file exists on your filesystem."
            fi;
          done;